<a href="https://colab.research.google.com/github/Bird120/DeepLearning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# **List**

In [ ]:
my_list = [[1,2,3,4,5,6], [7,8,9,10,11]]

In [ ]:
my_list

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11]]

# **Numpy Arrays**

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.17755055, 0.50518362, 0.75695636, 0.08778267],
       [0.73711838, 0.04492485, 0.92086535, 0.31268042],
       [0.82160028, 0.66589586, 0.67078578, 0.59532143]])

In [15]:
np1.dtype

dtype('float64')

# **Tensors**

In [16]:
tensor_2d = torch.randn(3,4)
tensor_2d


tensor([[-1.7245, -0.5820, -0.6948,  0.3756],
        [-0.3179,  0.2538,  0.5780,  0.1740],
        [ 1.2354,  0.6387, -0.9178, -0.1706]])

In [17]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
#Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1776, 0.5052, 0.7570, 0.0878],
        [0.7371, 0.0449, 0.9209, 0.3127],
        [0.8216, 0.6659, 0.6708, 0.5953]], dtype=torch.float64)

In [19]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [21]:
torch.ones([2, 4], dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)