<a href="https://colab.research.google.com/github/Bird120/DeepLearning/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
#Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [6]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [7]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
#Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
#remainder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
torch.remainder(tensor_b, tensor_a)


tensor([0, 0, 1, 0])

In [16]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])